export { default as Header } from "./header/Header";
export { default as GoToBtn } from "./id-btn/GoToId";
export { default as Footer } from "./footer/Footer";
export { default as DashBoard } from "./dashboard/Dashboard";
export { default as WheelCarousel } from "./wheel-slider/WheelSlider";
export { default as Heading } from "./heading/Heading";
export { default as FeatureBox } from "./feature-box/FeatureBox";
export { default as JumboSection } from "./jumbo/JumboSection";
export { default as Contact } from "./contact/Contact";
